export const USER_CHANNEL_OPTION = "USER_CHANNEL_OPTION"
export const ADD_CHANNEL = "ADD_CHANNEL"
export const ADD_FAVORITE_CHANNEL = "ADD_FAVORITE_CHANNEL"
export const GET_USER_INFO = "GET_USER_INFO"



export const DISPLAY_CHAT_ROOM = "DISPLAY_CHAT_ROOM"
export const UPON_CHANGE_CHANNEL = "UPON_CHANGE_CHANNEL"
